# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('jsonlist', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
