# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
