# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 07:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='message', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='brightness',
            field=models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='effect',
            field=models.IntegerField(choices=[(0, 'Static'), (1, 'Scroll')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='showtime',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
