# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 11:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_savedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='showtime',
            field=models.SmallIntegerField(default=10, help_text='test', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
