# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:57
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(upload_to=users.models.content_file_name),
        ),
    ]
