# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160904_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to=users.models.content_file_name),
        ),
    ]
