# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 12:36
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160918_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='/static/dist/img/404_user.png', storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=users.models.content_file_name),
        ),
    ]
