# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 05:47
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='markers',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
