# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160907_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='picture',
            field=models.ImageField(upload_to=map.models.content_file_name),
        ),
    ]
