# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:17
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20160919_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/map/picture/'), upload_to=b''),
        ),
    ]
