# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:20
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20160921_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b''),
        ),
    ]
